on:
  push:
    branches:
   #   - 'main'
   #   - '!test'
   #   - '!development'
    - '*' 
   
  workflow_dispatch:

name: 'Run Terraform Plan'

defaults:
  run:
    working-directory: ./terraform

env:
  TERRAFORM_VERSION: 1.3.6
  ARM_SUBSCRIPTION_ID: edb776c0-b5bb-40b3-aab5-c163c05da0d1
  ARM_TENANT_ID: a4d4d5cd-20cf-444e-bfe7-3d3ecef3fe94
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-1


jobs:
  terraform_plan:
    strategy:
      matrix:
        workspace: ['dev', 'prod']

    name: 'Terraform Branch Plan'
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: ${{ matrix.workspace }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.3.2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Validate
      run: terraform validate    

    - name: Terraform Plan
      run: terraform plan -var-file=vars/${{ env.TF_WORKSPACE }}.tfvars -out=terraform.plan
      